# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Super_Mario/super_mario/clk_wiz_0_1/clk_wiz_0_1.xci
# IP: The module: 'clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Lab6_1/Lab6_1.gen/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Lab6_1/Lab6_1.gen/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Lab6_1/Lab6_1.gen/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Super_Mario/super_mario/clk_wiz_0_1/clk_wiz_0_1.xci
# IP: The module: 'clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Lab6_1/Lab6_1.gen/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Lab6_1/Lab6_1.gen/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Lab6_1/Lab6_1.gen/sources_1/ip/clk_wiz_0_1/clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
