# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Super_Mario/super_mario/super_mario.srcs/sources_1/bd/bd_mario/ip/bd_mario_axi_gpio_3_0/bd_mario_axi_gpio_3_0.xci
# IP: The module: 'bd_mario_axi_gpio_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Super_Mario/super_mario/super_mario.gen/sources_1/bd/bd_mario/ip/bd_mario_axi_gpio_3_0/bd_mario_axi_gpio_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mario_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Super_Mario/super_mario/super_mario.gen/sources_1/bd/bd_mario/ip/bd_mario_axi_gpio_3_0/bd_mario_axi_gpio_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mario_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Super_Mario/super_mario/super_mario.gen/sources_1/bd/bd_mario/ip/bd_mario_axi_gpio_3_0/bd_mario_axi_gpio_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mario_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Super_Mario/super_mario/super_mario.srcs/sources_1/bd/bd_mario/ip/bd_mario_axi_gpio_3_0/bd_mario_axi_gpio_3_0.xci
# IP: The module: 'bd_mario_axi_gpio_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Super_Mario/super_mario/super_mario.gen/sources_1/bd/bd_mario/ip/bd_mario_axi_gpio_3_0/bd_mario_axi_gpio_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mario_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Super_Mario/super_mario/super_mario.gen/sources_1/bd/bd_mario/ip/bd_mario_axi_gpio_3_0/bd_mario_axi_gpio_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mario_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Super_Mario/super_mario/super_mario.gen/sources_1/bd/bd_mario/ip/bd_mario_axi_gpio_3_0/bd_mario_axi_gpio_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_mario_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
