# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Super_Mario/super_mario/mario_constraints.xdc

# Block Designs: bd/bd_mario/bd_mario.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario || ORIG_REF_NAME==bd_mario} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_microblaze_0_0/bd_mario_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_microblaze_0_0 || ORIG_REF_NAME==bd_mario_microblaze_0_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_mig_7series_0_0/bd_mario_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_mig_7series_0_0 || ORIG_REF_NAME==bd_mario_mig_7series_0_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_xbar_0/bd_mario_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_xbar_0 || ORIG_REF_NAME==bd_mario_xbar_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_auto_pc_7/bd_mario_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_auto_pc_7 || ORIG_REF_NAME==bd_mario_auto_pc_7} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_auto_pc_0/bd_mario_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_auto_pc_0 || ORIG_REF_NAME==bd_mario_auto_pc_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_auto_pc_1/bd_mario_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_auto_pc_1 || ORIG_REF_NAME==bd_mario_auto_pc_1} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_auto_pc_2/bd_mario_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_auto_pc_2 || ORIG_REF_NAME==bd_mario_auto_pc_2} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_auto_pc_3/bd_mario_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_auto_pc_3 || ORIG_REF_NAME==bd_mario_auto_pc_3} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_auto_pc_4/bd_mario_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_auto_pc_4 || ORIG_REF_NAME==bd_mario_auto_pc_4} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_auto_pc_5/bd_mario_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_auto_pc_5 || ORIG_REF_NAME==bd_mario_auto_pc_5} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_auto_pc_6/bd_mario_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_auto_pc_6 || ORIG_REF_NAME==bd_mario_auto_pc_6} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_microblaze_0_axi_periph_0/bd_mario_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_microblaze_0_axi_periph_0 || ORIG_REF_NAME==bd_mario_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_microblaze_0_axi_intc_0/bd_mario_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_microblaze_0_axi_intc_0 || ORIG_REF_NAME==bd_mario_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_microblaze_0_xlconcat_0/bd_mario_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_microblaze_0_xlconcat_0 || ORIG_REF_NAME==bd_mario_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_mdm_1_0/bd_mario_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_mdm_1_0 || ORIG_REF_NAME==bd_mario_mdm_1_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_rst_mig_7series_0_83M_0/bd_mario_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==bd_mario_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_axi_uartlite_0_0/bd_mario_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_axi_uartlite_0_0 || ORIG_REF_NAME==bd_mario_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_axi_timer_0_0/bd_mario_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_axi_timer_0_0 || ORIG_REF_NAME==bd_mario_axi_timer_0_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_axi_gpio_0_0/bd_mario_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_axi_gpio_0_0 || ORIG_REF_NAME==bd_mario_axi_gpio_0_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_clk_wiz_0_0/bd_mario_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_clk_wiz_0_0 || ORIG_REF_NAME==bd_mario_clk_wiz_0_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_rst_clk_wiz_0_124M_1/bd_mario_rst_clk_wiz_0_124M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_rst_clk_wiz_0_124M_1 || ORIG_REF_NAME==bd_mario_rst_clk_wiz_0_124M_1} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_spi_usb_0/bd_mario_spi_usb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_spi_usb_0 || ORIG_REF_NAME==bd_mario_spi_usb_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_axi_gpio_2_0/bd_mario_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_axi_gpio_2_0 || ORIG_REF_NAME==bd_mario_axi_gpio_2_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_axi_gpio_3_0/bd_mario_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_axi_gpio_3_0 || ORIG_REF_NAME==bd_mario_axi_gpio_3_0} -quiet] -quiet

# IP: bd/bd_mario/ip/bd_mario_rgb2dvi_0_0/bd_mario_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mario_rgb2dvi_0_0 || ORIG_REF_NAME==bd_mario_rgb2dvi_0_0} -quiet] -quiet

# XDC: c:/Super_Mario/super_mario/super_mario.gen/sources_1/bd/bd_mario/bd_mario_ooc.xdc
